# Generated by Django 2.2.1 on 2019-05-31 03:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 5, 31, 3, 7, 44, 559897, tzinfo=utc))),
            ],
        ),
    ]
