# Generated by Django 2.2.1 on 2019-05-31 03:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 31, 3, 26, 25, 20155, tzinfo=utc)),
        ),
    ]
