# Generated by Django 2.2.1 on 2019-05-31 04:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_auto_20190531_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 31, 4, 24, 35, 354173, tzinfo=utc)),
        ),
    ]
