# Generated by Django 2.2.1 on 2019-05-31 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_auto_20190531_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
