# Generated by Django 2.2.1 on 2019-05-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_auto_20190531_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
