# Generated by Django 2.2.1 on 2019-05-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_auto_20190531_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='History',
        ),
    ]
